[build]
  command = "npm install"
  publish = "src/web"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@xenova/transformers"]
